# Site settings
title: "John's Coding Cave"
url: "https://blog.johnverbiest.be"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
description: Turning ideas into working software since 2006.

# Your information
email: john@johnverbiest.be
author: John Verbiest
avatar: "//www.gravatar.com/avatar/55d07ea5ab0fdc21a29c10eed2be1be8?d=mm&s=135"
profile: Turning ideas into working software since 2006.
twitter_username: John_Verbiest
#github_username:  johnverbiest
profile_links:
  Email: "mailto:john@johnverbiest.be"
  LinkedIn: "https://www.linkedin.com/in/john-verbiest/"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service 
disqus_shortname: blog-johnverbiest-be 

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/

permalink: pretty
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
